import React from 'react';

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
      <p className="text-sm text-muted-foreground mb-4">Last Updated: April 9, 2025</p>
      
      {/* --- START: TERMS CONTENT --- */}
      <div className="prose dark:prose-invert max-w-none">

        <p className="mb-4">Welcome to AI Garden! These Terms and Conditions (&quot;Terms&quot;) govern your access to and use of the AI Garden website and services (collectively, the &quot;Service&quot;), operated by AI Garden (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).</p>
        <p className="mb-4">Please read these Terms carefully. By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not access or use the Service.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">1. Acceptance of Terms</h2>
        <p className="mb-4">By creating an account or using the Service, you affirm that you are at least 13 years old (or the age of majority in your jurisdiction, if higher) and capable of entering into a binding agreement, and you agree to comply with these Terms.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">2. Description of Service</h2>
        <p className="mb-4">AI Garden provides an interface allowing users to interact with various third-party large language models (LLMs). Users can optionally choose to store their chat history for conversational memory purposes.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">3. User Accounts</h2>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li><strong>Registration:</strong> You must register for an account to access the Service, providing accurate and complete information (name, email, password).</li>
          <li><strong>Security:</strong> You are responsible for maintaining the confidentiality of your account password and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. We are not liable for any loss or damage arising from your failure to protect your password or account information.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">4. User Conduct and Acceptable Use</h2>
        <p className="mb-4">You agree not to use the Service for any unlawful purpose or in any way that violates these Terms. You agree not to:</p>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li>Submit false or misleading information.</li>
          <li>Harass, abuse, defame, or threaten others.</li>
          <li>Transmit any content that is infringing, obscene, libelous, or otherwise objectionable.</li>
          <li>Use the Service to generate content that promotes illegal activities, hate speech, discrimination, or harm to individuals or groups.</li>
          <li>Attempt to gain unauthorized access to the Service, other user accounts, or our computer systems or networks.</li>
          <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          <li>Reverse engineer, decompile, or disassemble any portion of the Service.</li>
          <li>Use any automated means (bots, scrapers) to access the Service without our express written permission.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">5. User-Generated Content (Chat History)</h2>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li><strong>Optional Storage:</strong> As described in our Privacy Policy, you have the option to store your chat history (prompts and responses).</li>
          <li><strong>Responsibility:</strong> You are solely responsible for the content of your prompts and any consequences arising from them.</li>
          <li><strong>No Ownership Claim by AI Garden:</strong> If you choose to store your chat history, AI Garden does not claim ownership over your prompts or the responses generated by the third-party LLMs based on those prompts. Your stored chat history is primarily for your use within the Service.</li>
          <li><strong>Third-Party LLM Use:</strong> Responses are generated by third-party LLMs. We do not control the output of these models.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">6. Intellectual Property Rights</h2>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li><strong>Our Service:</strong> The Service itself, including its design, software, text, graphics, logos, and underlying technology, is the property of AI Garden or its licensors and is protected by copyright, trademark, and other intellectual property laws. We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service solely for your personal, non-commercial use according to these Terms.</li>
          <li><strong>Third-Party Models:</strong> The underlying AI models are the property of their respective creators/providers.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">7. Disclaimers Regarding AI Models</h2>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li><strong>No Guarantee of Accuracy:</strong> The AI models accessed through the Service can make mistakes, provide inaccurate information, or generate biased or offensive content. You should independently verify any critical information received from the AI models.</li>
          <li><strong>Use &quot;As Is&quot;:</strong> The Service and the AI-generated responses are provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</li>
          <li><strong>No Professional Advice:</strong> Information provided by the AI models does not constitute professional advice (e.g., legal, financial, medical). Always consult with a qualified professional for specific advice.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">8. Termination</h2>
        <ul className="list-disc list-inside mb-4 space-y-1">
          <li><strong>By You:</strong> You may terminate your account at any time by contacting us at colenielson6@gmail.com or through account settings if available.</li>
          <li><strong>By Us:</strong> We reserve the right to suspend or terminate your access to the Service, with or without notice, for any reason, including, but not limited to, a breach of these Terms. Upon termination, your right to use the Service will immediately cease. Provisions of these Terms that by their nature should survive termination shall survive (including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability).</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-3">9. Limitation of Liability</h2>
        <p className="mb-4">To the fullest extent permitted by applicable law, in no event shall AI Garden, its affiliates, directors, employees, or agents be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service (including third-party LLMs); (iii) any content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">10. Indemnification</h2>
        <p className="mb-4">You agree to defend, indemnify, and hold harmless AI Garden and its licensee and licensors, and their employees, contractors, agents, officers, and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney&apos;s fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) content posted or generated through your use of the Service.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">11. Governing Law</h2>
        <p className="mb-4">These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction - Placeholder, needs legal input], without regard to its conflict of law provisions.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">12. Changes to Terms</h2>
        <p className="mb-4">We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide reasonable notice prior to any new terms taking effect (e.g., via email or a notice on the Service). What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">13. Contact Us</h2>
        <p className="mb-4">If you have any questions about these Terms, please contact us at: colenielson6@gmail.com</p>

      </div>
      {/* --- END: TERMS CONTENT --- */}
    </div>
  );
} 